name: Test & Build Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Create .env from GitHub Secrets
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> .env
      - name: Run unit tests with coverage
        run: npx vitest run --coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage
          path: coverage

  build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build production
        run: npm run build
