<<<<<<< HEAD
name: Test & Build Main
=======
name: Deploy to Production
>>>>>>> 034686e34e475a9b379fe006e0987e4422ad57fc

on:
  push:
    branches:
      - main
  workflow_dispatch:

<<<<<<< HEAD
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Create .env from GitHub Secrets
=======
permissions:
  contents: read
  deployments: write
  pull-requests: write
  id-token: write

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create test environment file
>>>>>>> 034686e34e475a9b379fe006e0987e4422ad57fc
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> .env
<<<<<<< HEAD
      - name: Run unit tests with coverage
        run: npx vitest run --coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage
          path: coverage

  build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build production
        run: npm run build
=======

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: production
      url: https://10xcards.pl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create production environment file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> .env

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare Pages
        run: npx wrangler@3 pages deploy dist --project-name=10x --branch=main --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
>>>>>>> 034686e34e475a9b379fe006e0987e4422ad57fc
